version: '2.3'

services:
  database:
    ports:
      - 3306:3306
    logging:
      driver: json-file

  blockchain:
    ports:
      - 8545:8545
    logging:
      driver: json-file

  server:
    volumes:
      - server:/usr/local/app
    ports:
      - 3000:3000
    logging:
      driver: json-file
    command: bash -c "npm install && truffle migrate && sequelize db:migrate && npm run watch"

  web:
    volumes:
      - web:/usr/local/app
    ports:
      - 80:3000
      - 8080:80
    logging:
      driver: json-file
    command: bash -c "npm install && nginx -g 'daemon on;' && npm run dev"

volumes:
  server:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr
      device: ":${APP_ROOT}/server"
  web:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr
      device: ":${APP_ROOT}/web"
