FROM node:9

RUN echo '#!/bin/bash' > /usr/local/bin/entrypoint.sh \
  && echo 'npm install' >> /usr/local/bin/entrypoint.sh \
  && chmod +x /usr/local/bin/entrypoint.sh
  && echo 'exec "$@"' >> /usr/local/bin/entrypoint.sh

ADD init $APP_ADD_PATH /usr/local/

RUN chown -R node /usr/local/init $APP_ADD_PATH

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
