version: '2.3'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-db
    networks:
      - network
    volumes:
      - database:/var/lib/mysql
    logging:
      driver: journald
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  blockchain:
    build:
      context: .
      dockerfile: Dockerfile-blockchain
    networks:
      - network
    volumes:
      - blockchain:/var/lib/blockchain
    logging:
      driver: journald
    environment:
      DOCKER: 'true'
    command: "-a '1' -m '${ETH_MNEMONIC}' -i '1' --db=/var/lib/blockchain"

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      - network
    depends_on:
      - database
      - blockchain
    logging:
      driver: journald
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      ETH_ADDRESS: ${ETH_ADDRESS}
      ETH_KEY: ${ETH_KEY}
      ETH_HOST: ${ETH_HOST}
      ETH_PORT: ${ETH_PORT}
      PATH: /usr/local/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: bash -c "sleep 10 && truffle migrate && sequelize db:migrate && npm start"

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      args:
        api_host: ${API_HOST}
        api_port: ${API_PORT}
    networks:
      - network
    ports:
      - 80
    depends_on:
      - server
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    logging:
      driver: journald
    command: bash -c "nginx -g 'daemon off;'"

networks:
  network:

volumes:
  database:
  blockchain:
