version: '2.3'

services:
  db:
    image: mysql:5.7
    networks:
      - app_net
    volumes:
      - app_db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      - app_net
    user: node

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    depends_on:
      - app
      - db
    networks:
      - app_net
    command: nginx

networks:
  app_net:

volumes:
  app_db:
