FROM node:9

# RUN \
#   apt-get update \
#   && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ssmtp \
#   && rm -rf /usr/share/locale/* \
#   && rm -rf /var/cache/debconf/*-old \
#   && rm -rf /var/lib/apt/lists/* \
#   && rm -rf /usr/share/doc/*
#
# RUN \
#   echo "root=postmaster" >> /etc/ssmtp/ssmtp.conf \
#   && echo "FromLineOverride=yes" >> /etc/ssmtp/ssmtp.conf \
#   && echo "mailhub=${SMTP_HOST}" >> /etc/ssmtp/ssmtp.conf \
#   && echo "UseTLS=yes" >> /etc/ssmtp/ssmtp.conf \
#   && echo "AuthUser=${SMTP_USER}" >> /etc/ssmtp/ssmtp.conf \
#   && echo "AuthPass=${SMTP_PASSWORD}" >> /etc/ssmtp/ssmtp.conf

ADD server/package.json server/package-lock.json /usr/local/app/
WORKDIR /usr/local/app/
RUN npm install --only=production
ADD server /usr/local/app/
