version: '2.3'

services:
  db:
    image: mysql:5.7
    networks:
      - app_net
    volumes:
      - app_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      - app_net
    user: node
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      PATH: /usr/local/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    depends_on:
      - server
      - db
    networks:
      - app_net

networks:
  app_net:

volumes:
  app_db:
