version: '2.3'

services:
  db:
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    volumes:
      - ./app:/usr/local/app
      - ./app/node_modules:/usr/local/app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      PATH: /usr/local/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: bash -c "npm install && npm run watch"

  web:
    volumes_from:
      - app
    ports:
      - 80:80
