version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    image: node:9
    user: "node"
    working_dir: /usr/local/app
    volumes:
      - ./app:/usr/local/app
      - ./app/node_modules:/usr/local/app/node_modules
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    # command: bash -c "npm install && npm run start"
    command: bash -c "npm install && npm run watch"

  web:
    build: web
    ports:
      - 80:80
    volumes_from:
      - app
    volumes:
      - ./web/logs:/var/log/nginx
    depends_on:
      - app
      - db
    command: nginx
