FROM debian:latest

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install nginx curl gnupg2 ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install build-essential libssl-dev nodejs \
    && rm -rf /usr/share/locale/* \
    && rm -rf /var/cache/debconf/*-old \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc/*

RUN \
    sed "s/access_log.*/access_log \/dev\/stdout;/g" -i /etc/nginx/nginx.conf \
    && sed "s/error_log.*/error_log \/dev\/stderr;/g" -i /etc/nginx/nginx.conf

RUN \
    echo 'server {' > /etc/nginx/sites-enabled/default \
    && echo '  listen 80;' >> /etc/nginx/sites-enabled/default \
    && echo '  server_name _;' >>  /etc/nginx/sites-enabled/default \
    && echo '  charset utf-8;' >>/etc/nginx/sites-enabled/default \
    && echo '  location / {' >>/etc/nginx/sites-enabled/default \
    && echo '    alias /usr/local/app/dist/;' >>  /etc/nginx/sites-enabled/default \
    && echo '  }' >> /etc/nginx/sites-enabled/default \
    && echo '  location /api/ {' >>  /etc/nginx/sites-enabled/default \
    && echo '    proxy_pass http://server:3000/;' >> /etc/nginx/sites-enabled/default \
    && echo '    proxy_set_header Host $host;' >>/etc/nginx/sites-enabled/default \
    && echo '    proxy_set_header X-Real-IP $remote_addr;' >>/etc/nginx/sites-enabled/default \
    && echo '    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;' >>/etc/nginx/sites-enabled/default \
    && echo '  }' >> /etc/nginx/sites-enabled/default \
    && echo '}' >> /etc/nginx/sites-enabled/default

ADD web/package.json web/package-lock.json /usr/local/app/
WORKDIR /usr/local/app/
RUN npm install --only=production
ADD web /usr/local/app/
RUN npm run build
