version: '2'

services:
  db:
    ports: []
    volumes:
      - ./db/mysql:/var/lib/mysql

  app:
    ports: []
    volumes:
      - ./app:/usr/local/app
      - ./app/node_modules:/usr/local/app/node_modules
    command: bash -c "npm install && npm run start"

  web:
    ports:
      - 443:443
