version: '2.3'

services:
  db:
    ports:
      - 3306:3306

  server:
    volumes:
      - ./server:/usr/local/app
      - ./server/node_modules:/usr/local/app/node_modules
    ports:
      - 9000:9000
    command: bash -c "npm install && npm run watch"

  web:
    volumes:
      - ./client:/usr/local/app
      - ./client/node_modules:/usr/local/app/node_modules
    ports:
      - 80:80
      - 3000:3000
    command: bash -c "npm install && nginx"
