version: '2'

services:
  db:
    ports: []
    volumes:
      - oblatum_database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    ports: []
    user: "node"
    working_dir: /usr/local/app
    volumes:
      - ./app:/usr/local/app
      - ./app/node_modules:/usr/local/app/node_modules
    environment:
      PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    command: bash -c "npm install && npm run start"

  web:
    ports:
      - 443:443
    volumes_from:
      - app
    depends_on:
      - app
      - db
    command: nginx
