version: '2.3'

services:
  db:
    ports:
      - 3306:3306

  server:
    depends_on:
      - db
      - blockchain
    volumes:
      - ./server:/usr/local/app
      - ./server/node_modules:/usr/local/app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run watch"

  web:
    volumes:
      - ./client:/usr/local/app
      - ./client/node_modules:/usr/local/app/node_modules
    ports:
      - 80:80
      - 8080:8080
    # command: bash -c "npm install && nginx"
    # To be able to do this we need to remove daemon directive from /etc/nginx/nginx.conf:
    command: bash -c "npm install && nginx -g 'daemon on;' && npm run dev"

  blockchain:
    build:
      context: .
      dockerfile: Dockerfile-blockchain
    volumes:
      - ./blockchain:/usr/local/app
      - ./blockchain/node_modules:/usr/local/app/node_modules
    networks:
      - app_net
    user: node
    environment:
      NODE_ENV: ${NODE_ENV}
      PATH: /usr/local/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 8545:8545
    command: bash -c "npm install && npm start"
