version: '2.3'

services:
  app:
    volumes:
      - ./app:/usr/local/app
      - ./app/node_modules:/usr/local/app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run watch"

  web:
    volumes_from:
      - app
    ports:
      - 80:80
